apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sb-angular-backend
  labels:
    app: sb-angular-backend
    project: sb-angular
  annotations:
    author: "Patrice CAVEZZAN"
    email: "pcavezzan@gmail.com"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: sb-angular.apps.codeinlove.fr
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: sb-angular-backend
                port:
                  name: http