apiVersion: v1
kind: Secret
metadata:
  name: sb-angular-backend-secrets
  labels:
    app: sb-angular-backend
    project: sb-angular
data:
  backend.messages.welcome: SGVsbG8gV29ybGQgaW5zaWRlIEt1YmVybmV0ZXMgZnJvbSAke3NwcmluZy5hcHBsaWNhdGlvbi5uYW1lfQo=