apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sb-angular-store-data
  labels:
    app: sb-angular-store
    project: sb-angular
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi