apiVersion: v1
kind: Service
metadata:
  name: sb-angular-cluster-store
spec:
  clusterIP: None
  selector:
    app: sb-angular-cluster-store
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sb-angular-store
  labels:
    app: sb-angular-cluster-store
    project: sb-angular
  annotations:
    author: "Patrice CAVEZZAN"
    email: "pcavezzan@gmail.com"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sb-angular-cluster-store
      project: sb-angular
  serviceName: sb-angular-cluster-store
  template:
    metadata:
      name: store
      labels:
        app: sb-angular-cluster-store
        project: sb-angular
      annotations:
        author: "Patrice CAVEZZAN"
        email: "pcavezzan@gmail.com"
    spec:
      imagePullSecrets:
        - name: pcavezzan.azurecr.io
      containers:
        - name: main
          image: pcavezzan.azurecr.io/pcavezzan/sb-angular-store:v2.0.0
          args:
            - "--enableClustering"
            - "--id=$(INSTANCE_ID).sb-angular-cluster-store"
            - "--clusterMembers=sb-angular-store-0.sb-angular-cluster-store:9090,sb-angular-store-1.sb-angular-cluster-store:9090"
          env:
            - name: INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 9090
              name: http
          volumeMounts:
            - mountPath: /app/data
              name: sb-angular-store-data
          livenessProbe:
            httpGet:
              port: http
              path: /ping
          readinessProbe:
            httpGet:
              port: http
              path: /ping
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
  volumeClaimTemplates:
    - metadata:
        name: sb-angular-store-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi