apiVersion: v1
kind: ConfigMap
metadata:
  name: sb-angular-frontend-config
  labels:
    app: sb-angular-frontend
    project: sb-angular
data:
  environment.json: |
    {
      "config": {
        "env": "kubernetes",
        "curl": {
          "active": false,
          "timeInMillis": 5000
        }
      }
    }
