apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sb-angular-frontend-config-pvc
  labels:
    app: sb-angular-front
    project: sb-angular
  annotations:
    author: "Patrice CAVEZZAN"
    email: "pcavezzan@gmail.com"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi